# Generated by Django 4.1.3 on 2022-11-27 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogdetailpage",
            name="excerpt",
            field=models.CharField(max_length=250, null=True),
        ),
    ]
