# Generated by Django 4.1.3 on 2022-11-25 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0078_referenceindex"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialMediaSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "linkedin",
                    models.URLField(blank=True, help_text="LinkedIn link.", null=True),
                ),
                (
                    "instagram",
                    models.URLField(blank=True, help_text="Instagram link.", null=True),
                ),
                (
                    "facebook",
                    models.URLField(blank=True, help_text="FaceBook link.", null=True),
                ),
                (
                    "twitter",
                    models.URLField(blank=True, help_text="Twitter link.", null=True),
                ),
                (
                    "youtube",
                    models.URLField(blank=True, help_text="YouTube link.", null=True),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
