# Generated by Django 4.1.3 on 2022-11-25 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0024_index_image_file_hash"),
        ("wagtailvideos", "0014_alter_tracklisting_id_alter_video_id_and_more"),
        ("flex", "0006_alter_flexpage_content_flexcarousel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flexcarousel",
            name="carousel_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AlterField(
            model_name="flexcarousel",
            name="carousel_video",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailvideos.video",
            ),
        ),
    ]
