# Generated by Django 4.1.3 on 2022-11-25 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flex", "0007_alter_flexcarousel_carousel_image_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="FlexCarousel",),
    ]
