# Generated by Django 4.1.3 on 2022-11-25 01:41

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import wagtail.fields
import wagtailsvg.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailsvg", "0005_alter_svg_file"),
        ("wagtailimages", "0024_index_image_file_hash"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteLogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Site main logo", max_length=100, null=True
                    ),
                ),
                (
                    "logo_slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True, editable=False, populate_from="name"
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("svg", wagtailsvg.blocks.SvgChooserBlock())],
                        blank=True,
                        use_json_field=None,
                    ),
                ),
                (
                    "main_logo_svg",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailsvg.svg",
                    ),
                ),
                (
                    "site_logo_image",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
        ),
    ]
